### ISSUE TITLE
LANGUAGE SUPPORT for Stata '.ado、.do' 

### ISSUE THREAD

**Issue by PatricksonFang** [allemand-instable/Colorful-Comments#10]
Thanks.

**Comment by code-instable** [comment]
Hey, could you please specify the format of the comments please ? I don't use those

I need :
- inline comment syntax
- multiline/block comment : begin and closing tags for commenting
- language identifier in vscode ( not the extension, what's shown in parenthesis when you switch language in vscode )

I will then add it as soon as possible

**Comment by code-instable** [comment]
hello, I figured out that stata language support is already implemented 

```yaml
sas_stata_format: &sas_stata_format
  <<: *base
  commentFormat: ["*", "/*", "*/"]
...
stata: *sas_stata_format
```

so please make sure that you use the correct language identifier in vscode ( select stata as working language)
the language id should be (stata)
