### ISSUE TITLE
SystemVerilog ( Parth2031/Colorful-Comments #12 )

### ISSUE THREAD

**Issue by code-instable** [allemand-instable/Colorful-Comments#2]
> Hi - can you please add support for SystemVerilog files (and maybe VHDL files too)? this is the main language we use

- from [jonnyboynewton](https://github.com/jonnyboynewton)
- [original issue](https://github.com/Parth2031/Colorful-Comments/issues/12)

**level of details :** extremely low, more details would be appreciated ( comment syntax, language identifier )

- needed to work all by myself

- VHDL and SystemVerilog do not have the same comment syntax, had to figure out by myself ( details would have been appreciated )

Ressources :
- extension : https://github.com/mshr-h/vscode-verilog-hdl-support

**Comment by code-instable** [comment]
suggested fix :

- languageConfig.yaml

```yaml
  # * SystemVerilog
  # https://github.com/Parth2031/Colorful-Comments/issues/12
  # according to extension : mshr-h.veriloghdl
  # github : https://github.com/mshr-h/vscode-verilog-hdl-support
  systemverilog: *c_delim
  vhdl: *double_dash_delim
```
