### ISSUE TITLE
[LANGUAGE] SQL

### ISSUE THREAD

**Issue by xhorntail** [allemand-instable/Colorful-Comments#8]
While the single line `--` comments work, block comments don't.

If I understand the documentation correctly, it should just be this..

```yaml
python_delim: &sql_delim
  <<: *base
  commentFormat: [, '/*', '*/']
```

Or, if you want to be explicit with type definition rather than using the `*double-dash-delim` (just for ease of copy/paste)

```yaml
python_delim: &sql_delim
  <<: *base
  commentFormat: ["--", '/*', '*/']
```

Thanks for carrying the torch on this project!

(edit:) sql, not python 😳
